server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  context-path: /demo

spring:
  profiles:
    active:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect




